### ISSUE TITLE
Checkbox Label

### ISSUE THREAD

**Issue by Ghostavio** [jonnii/ember-cli-lightning-design-system#6]
When using checkboxes, we get a hardcoded label `Checkbox Label`, there's no option of setting a label for the checkbox or radio button at the moment.

**Comment by jonnii** [comment]
@Ghostavio yeah i haven't got around to that one yet! I'm still working on the form controls. I would recommend only using the controls in the readme so far. Happy for PRs though, I'll keep this open as a reminder.

**Comment by jonnii** [comment]
@Ghostavio I'm going to merge https://github.com/jonnii/ember-cli-lightning-design-system/pull/7 which is for checkbox groups. I'm going to do another PR to cover the single checkbox, which should be straightforward. Let me know if this solves your issue.
